POST http://localhost:7071/api/ConvertCSVToJson HTTP/1.1
content-type: text/plain

Group:PATIENT
Fields:|PATNO|LASTNAME|FIRNAME|MIDNAME|TITLE|SUFFIX|PATID|PATBIRTH|PATSEX|NAME1|PATID1|OCCUPAT|HL7LOCK|PATHIST|PATCOM|ADDRESS|ETHNIC|MILRANK|PID|CONFLICT|ORIGIN|SSNUMBER|SITEID|
|80983|Joe|Blog||||ABC1234|12/12/1912|2||||||||||2||5|||

Group:STUDY
Fields:|PATNO|SEQNO|REFNO|OPENED|ACQU|TIMEOUT|SIGNED|STUDATE|NCSTUID|UNIQID|REFPHYS|REQPHYS|DIAGNOSE|PATLOC|ADMISSID|INSTRES|STUDYID|ACCESSNO|REQPRID|REQPRDES|STUDESC|STUCOM|PATPOS|INSTNAME|PERPHYS1|PERPHYS2|OPNAME1|OPNAME2|PREMED|CONTRAST|MEDALERT|ALLERGY|SPECNEED|PATSTATE|SMOKING|PREGSTAT|MENSDATE|STATEID|PCATHTIM|ORDNUM|
|80983|1|81013|||||30/11/2020|1.3.12.2.1107.5.13.2.0.30000020111519210138500000130||||||||||||Vascular^Vascular||HFS|Intra Epsom|Dr. Brendan Buckley||Teresa Kerr|Sarah Scheirlinck||||||||Unknown||3|30/11/2020 09:28:05.543||

Group:PI
Fields:|REFNO|IDNR|LASTNAME|FIRNAME|UNIQID|EXAMFILE|
|81013|ABC1234|Joe|Blog|||

Group:PD
Fields:|REFNO|SEX|DOB|AGE|AGEUNIT|AGEDAYS|HEIGHT|WEIGHT|BSA|PREHB|
|81013|Male|12/12/1912|63|Years||185|81|1.97||

Group:ID
Fields:|REFNO|EXAMDATE|STATIME|PROCTIME|ENDTIME|
|81013|30/11/2020|08:29:11|58|09:28:00|

Group:C_ST
Fields:|REFNO|SEQNO|AUTOTIME|ID|DESCRPT|ACCNO|COMMENT|

Group:PN
Fields:|REFNO|SEQNO|AUTOTIME|PNNAME|STAFF|COMMENT|
|81013|21004|08:29:25|Euna Go|Circulator||

Group:CD
Fields:|REFNO|SEQNO|AUTOTIME|CLINDIAG|PREVTRT|COMMENT|

Group:ADM
Fields:|REFNO|SEQNO|AUTOTIME|STATA|ADMISA|COMMENT|

Group:CASE1
Fields:|REFNO|SEQNO|AUTOTIME|TOUT|STATIME|STOPTIME|COST|COMMENT|

Group:HIST
Fields:|REFNO|SEQNO|AUTOTIME|HISTR|COMMENT|

Group:ALE
Fields:|REFNO|SEQNO|AUTOTIME|ALLEG|COMMENT|

Group:SHE
Fields:|REFNO|SEQNO|AUTOTIME|SHEAT|SITEA|TIM|AIMLS|AIMLS1|CLOSD|COMMENT|

Group:PM
Fields:|REFNO|SEQNO|AUTOTIME|PREMED|AMOUNT|COMMENT|COMMEN1|

Group:PR
Fields:|REFNO|SEQNO|TIM|PROCEDUR|COMMENT|
|81013|16001|08:29|Varicocele Embolisation||
|81013|16002|08:29|Sonosite Ultrasound||

Group:EPP
Fields:|REFNO|SEQNO|TIM|EPPROCED|COMMENT|

Group:CA
Fields:|REFNO|SEQNO|AUTOTIME|CATHETER|REFEQ|COMMENT|
|81013|16001|08:37:29|5Fr Impulse MPA1 catheter 100cm|H749163911171| Expiry Date: 220811 Lot Number: 60253356|
|81013|16002|08:37:33|5F RADIFOCUS Introducer II 10cm|RS*B50N10MR5||

Group:CA1
Fields:|REFNO|SEQNO|AUTOTIME|LESI|ITM|PCIEQ|PCREF|ATM|TIM|COMMENT|

Group:ME
Fields:|REFNO|SEQNO|TIM|MEDIC|ADMIN|AMOUNT|PCREF|COMMENT|
|81013|16001|08:36|Fentanyl (µg)|Intravenous|50|Fentanyl 100mcg/2ml||
|81013|16002|08:36|Midazolam (mg)|Intravenous|2|Midazolam 5mg/5ml||
|81013|16003|08:43|Midazolam (mg)|Intravenous|1|Midazolam 5mg/5ml||
|81013|16004|08:54|Fibrovein 3% (ml)|Intravenous|2|||
|81013|16005|08:55|Lipiodol (ml)|Intravenous|2|||
|81013|16006|09:10|Fentanyl (µg)|Intravenous|25|Fentanyl 100mcg/2ml||

Group:METOTAL
Fields:|REFNO|SEQNO|AUTOTIME|MEDIC|TOTAL|COMMENT|
|81013|16001|08:43:18|Midazolam (mg)|3||
|81013|16002|09:10:42|Fentanyl (µg)|75||
|81013|16003|08:55:05|Fibrovein 3% (ml)|2||
|81013|16004|08:55:13|Lipiodol (ml)|2||

Group:AN
Fields:|REFNO|SEQNO|TIM|ANGISITE|ANGIDOSE|ANGITXT|CONTRAST|COMMENT|

Group:DIACO
Fields:|REFNO|SEQNO|AUTOTIME|DCOME|COMMENT|

Group:CONT
Fields:|REFNO|SEQNO|AUTOTIME|CONTR|CONTA|COMMENT|

Group:CONT1
Fields:|REFNO|SEQNO|AUTOTIME|CONTR|CONTA|PCREF|COMMENT|
|81013|9002|09:20|Omnipaque 300|25|||

Group:CM
Fields:|REFNO|SEQNO|TIM|COMPLIC|COMMENT|
|81013|16001|09:20|No complications||

Group:DC
Fields:|REFNO|SEQNO|TIM|COMTXT|

Group:PPC
Fields:|REFNO|SEQNO|TIM|POPR|COMMENT|

Group:CAV
Fields:|REFNO|SEQNO|AUTOTIME|CATHETER|REFEQ|LOTVN|COMMENT|
|81013|17001|09:04:48|Catheter 4Fr GLIDECATH Straight 65cm|RF*ZM7410GM|||

Group:PACGEN
Fields:|REFNO|SEQNO|AUTOTIME|PACGE|PGENS|PMASE|LRATE|URATE|GENSI|COMMENT|

Group:PACLED
Fields:|REFNO|SEQNO|AUTOTIME|PASITE|PACLE|PACESN|PACCO|PRWAVE|PTHRES|PACIMP|COMMENT|

Group:PHILDOSE
Fields:|REFNO|SEQNO|AUTOTIME|AIRKERMA|DAP|FLUOTIME|COMMENT|
|81013|9001|09:21:18|87|14490|13:52||

Group:PHLDOSE
Fields:|REFNO|SEQNO|AUTOTIME|AIRKERM|DAPROD|FLUTIME|COMMENT|

Group:EPC
Fields:|REFNO|SEQNO|TIM|COMTXT|

Group:OS
Fields:|REFNO|SEQNO|TIM|ITEM|SIZE_OF|AMOUNT|UNIT|COMMENT|

Group:FT
Fields:|REFNO|SEQNO|AUTOTIME|FLUOTIME|COMMENT|

Group:HT
Fields:|REFNO|SEQNO|AUTOTIME|HEMOTXT|

Group:AR
Fields:|REFNO|SEQNO|AUTOTIME|ANGIOTXT|

Group:DI
Fields:|REFNO|SEQNO|AUTOTIME|DIAGNOS|AETIOLOG|SEVERITY|COMMENT|

Group:CC
Fields:|REFNO|SEQNO|AUTOTIME|COMTXT|

Group:ECD
Fields:|REFNO|SEQNO|AUTOTIME|ECCODATE|EJECFRAC|VALVSTAT|CO|DOPFLO|COMMEN|

Group:ECF
Fields:|REFNO|SEQNO|AUTOTIME|ECCTXT|

Group:BA
Fields:|REFNO|SEQNO|AUTOTIME|BAKTXT|

Group:OP
Fields:|REFNO|SEQNO|AUTOTIME|PRCTXT|

Group:FI
Fields:|REFNO|SEQNO|AUTOTIME|CATTXT|

Group:CR
Fields:|REFNO|SEQNO|AUTOTIME|CORTXT|

Group:EPF
Fields:|REFNO|SEQNO|AUTOTIME|EPTXT|

Group:RS
Fields:|REFNO|SEQNO|AUTOTIME|RESTXT|

Group:RE
Fields:|REFNO|SEQNO|AUTOTIME|RECTXT|

Group:RVLEAD
Fields:|REFNO|SEQNO|AUTOTIME|MANFACT|MODELNR|SERIALNR|LEADTYP|CONNTYP|VEIN|COMMENT|

Group:CSLEAD
Fields:|REFNO|SEQNO|AUTOTIME|MANFACT|MODELNR|SERIALNR|LEADTYP|CONNTYP|VEIN|COMMENT|

Group:RALEAD
Fields:|REFNO|SEQNO|AUTOTIME|MANFACT|MODELNR|SERIALNR|LEADTYP|CONNTYP|VEIN|COMMENT|

Group:FINALPAC
Fields:|REFNO|SEQNO|AUTOTIME|MANFACT|MODELNR|SERIALNR|SENSTYP|LOCATN|BPACERT|APACEV|APACEMA|APLSWDTH|VPACEV|VPACEMA|VPLSWDTH|COMMENT|

Group:RAPOT
Fields:|REFNO|SEQNO|AUTOTIME|PWAVE|TRSHLD|IMPEAD|COMMENT|

Group:RVPOT
Fields:|REFNO|SEQNO|AUTOTIME|RWAVE|TRSHLD|IMPEAD|COMMENT|

Group:CSPOT
Fields:|REFNO|SEQNO|AUTOTIME|RWAVE|TRSHLD|IMPEAD|COMMENT|

Group:DEFIBTST
Fields:|REFNO|SEQNO|AUTOTIME|SHKIMPD|DEFTRSH|ATTDFT|SUCDFT|TOTENG|VFINDUC|COMMENT|

Group:FINALICD
Fields:|REFNO|SEQNO|AUTOTIME|MANFACT|MODELNR|SERIALNR|SENSTYP|LOCATN|ELECONF|FIBDET|FSHKJ|BPACERT|APACEV|APACEMA|APLSWDTH|VPACEV|VPACEMA|VPLSWDTH|ATPSTAT|COMMENT|

Group:EP_OP
Fields:|REFNO|SEQNO|AUTOTIME|PROCOM|

Group:EP_FI
Fields:|REFNO|SEQNO|AUTOTIME|INDIC|

Group:EP_RFA
Fields:|REFNO|SEQNO|AUTOTIME|RFACOM|

Group:EPCD
Fields:|REFNO|SEQNO|AUTOTIME|CVDIS|COMMENT|

Group:EPOD
Fields:|REFNO|SEQNO|AUTOTIME|ODIS|COMMENT|

Group:EPPT
Fields:|REFNO|SEQNO|AUTOTIME|TRTDATE|PREVTRT|TRTSITE|COMMENT|

Group:EPDA
Fields:|REFNO|SEQNO|AUTOTIME|ARRH|COMMENT|

Group:EPSY
Fields:|REFNO|SEQNO|AUTOTIME|SYMPT|SYSTRT|SYFRQ|SYEPDUR|SYPROV|COMMENT|

Group:EPLV
Fields:|REFNO|SEQNO|AUTOTIME|LVSPERF|EF|LVFASS|COMMENT|

Group:EPCM
Fields:|REFNO|SEQNO|AUTOTIME|TRTDRUG|AMOUNT|COMMENT|

Group:EPPS
Fields:|REFNO|SEQNO|AUTOTIME|PSITE|PCL|MAXES|COMMENT|

Group:EPRP
Fields:|REFNO|SEQNO|AUTOTIME|REFP|RPPSITE|RPPCL|RPVAL|COMMENT|

Group:EPAN
Fields:|REFNO|SEQNO|AUTOTIME|ACND|

Group:EPRE
Fields:|REFNO|SEQNO|AUTOTIME|RCND|

Group:EPIN
Fields:|REFNO|SEQNO|AUTOTIME|INFRAN|COMMENT|

Group:EPCV
Fields:|REFNO|SEQNO|TIM|CVTYPE|CVENERGY|COMMENT|

Group:EPAT
Fields:|REFNO|SEQNO|AUTOTIME|ABTARGET|COMMENT|

Group:EPAR
Fields:|REFNO|SEQNO|AUTOTIME|ABRES|

Group:EPSF
Fields:|REFNO|SEQNO|AUTOTIME|EPFNDNGS|

Group:EPAC
Fields:|REFNO|SEQNO|AUTOTIME|ADDCOM|

Group:EPCC
Fields:|REFNO|SEQNO|AUTOTIME|COMPLIC|THERAPY|COMMENT|

Group:EPRC
Fields:|REFNO|SEQNO|AUTOTIME|EPRECS|

Group:RSPETCO2
Fields:|REFNO|SEQNO|AUTOTIME|RESP|ETCO2|COMMENT|

Group:CTINTERV
Fields:|REFNO|SEQNO|AUTOTIME|S4E10|S2E1|S1E10|COMMENT|
|81013|17001|09:20:21|35||||

Group:_ESTEX2
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|INPCHA|OUTSITE|S1S1|S1S2|S2S3|S3S4|S4S5|

Group:_ESTC12
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|INPCHA|OUTSITE|PCL|

Group:_ESTC22
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|INPCHA|OUTSITE|PCL|

Group:_ESTD12
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|INPCHA|OUTSITE|PCLSTART|

Group:_ESTDY2
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|INPCHA|OUTSITE|PCLSTART|PCLSTOP|NOPULSES|

Group:INFCONN
Fields:|REFNO|CAREUNIT|BEDLABEL|HOSTNAME|SERVER|PATID|LASTNAME|FIRNAME|FRSTDATA|NEXTQRY|PREVQRY|IMPORTVS|LOFFTIME|USERACT|OFFSET|

Group:INFSTAT
Fields:|REFNO|LOGFMF|LOGFSAF|LOGMNF|

Group:INFVS
Fields:|REFNO|SEQNO|ATIME|HR|SYST|DIAST|MEAN|SPO2|RESP|ETCO2|INFVSCMT|

Group:ACQNAME
Fields:|REFNO|COMPUTER|SYSTTYPE|
|81013|SENSIS100206|DMC_CLIENT|

Group:E_RECON
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|

Group:E_RECOFF
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|

Group:E_SNPSHT
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|

Group:E_WAVEF
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|

Group:E_STIMEX
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|LABEL|PECHA|NECHA|PECHB|NECHB|S1S1|S1S2|S2S3|S3S4|S4S5|

Group:E_STIMC1
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|LABEL|PECHA|NECHA|PECHB|NECHB|PCL|

Group:E_STIMC2
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|

Group:E_STIMD1
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|LABEL|PECHA|NECHA|PECHB|NECHB|PCLSTART|

Group:E_STIMDY
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|LABEL|PECHA|NECHA|PECHB|NECHB|PCLSTART|PCLSTOP|NOPULSES|

Group:E_ABLAT1
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|EVSEQNO|

Group:E_ABLAT2
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|EVSEQNO|DURATION|AVTEMP|AVPOWER|AVIMPD|ENERGY|

Group:E_ABLAT3
Fields:|REFNO|EVENTLBL|EVENTCMT|NOABLS|DURATION|AVTEMP|MAXTEMP|AVIMPD|MAXIMPD|AVPOWER|MAXPOWER|ENERGY|

Group:E_TACHY1
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|CL|ONSET|

Group:E_TACHY2
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|

Group:E_BRADY1
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|CL|ONSET|

Group:E_BRADY2
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|

Group:E_ECG12
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|MORPH|

Group:E_INTERV
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|INTERV1|INTERV2|INTERV3|INTERV4|INTERV5|INTERV6|INTERV7|INTERV8|INTLAB1|INTLAB2|INTLAB3|INTLAB4|INTLAB5|INTLAB6|INTLAB7|INTLAB8|

Group:T_APLAST
Fields:|REFNO|DATETIME|EVENTLBL|EVENTCMT|INFLPRE|INFLDUR|

Group:T_VPLAST
Fields:|REFNO|DATETIME|EVENTLBL|EVENTCMT|INFLPRE|INFLDUR|

Group:T_CNTUP
Fields:|REFNO|DATETIME|EVENTLBL|EVENTCMT|ELAPSED|

Group:T_CNTDWN
Fields:|REFNO|DATETIME|EVENTLBL|EVENTCMT|ELAPSED|

Group:V_SIGNS
Fields:|REFNO|DATETIME|EVENTCMT|HR|SYST|DIAST|MEAN|O2|RESP|

Group:REPORT
Fields:|REPNO|FILENAME|REPDATE|REPSCOPE|PATNO|REFNO|TEMPLNO|EDITED|DRAFT|TIMEOUT|SIGNED|STORED|VERSION|OLDREPNO|MEDIA|MLABEL|SLABEL|
|9108|20201130092824_81013_207.doc|30/11/2020 09:28:24.000|STUDY|80983|81013|207||Y||||0|0||||

Group:EXPPATH
Fields:|REFNO|SEQNO|EXPPATH|

Group:HL7DATA
Fields:|REFNO|RECAPP|RECFAC|SENDAPP|SENDFAC|

Group:ABLGRIMG
Fields:|REFNO|ATIME|EVENTLBL|EVENTCMT|FILENAME|

Group:MPSYSIMG
Fields:|REFNO|ATIME|EVENTCMT|IMGNAME|IMGCMT|FILENAME|

Group:STUDYPIC
Fields:|REFNO|SEQNO|FILENAME|DESCRPT|

Group:STUDYWF
Fields:|REFNO|SEQNO|FILENAME|DESCRPT|

Group:PE
Fields:|REFNO|EDATE|

Group:PH
Fields:|REFNO|SEQNO|EXTDATE|

Group:UN
Fields:|REFNO|HB|UNWORK|RESIST|PO2|INFHR|INFSPO2|INFRESP|INFNBP|INFETCO2|ETCO2|
|81013|g/l|J|dynes*s/cm5|mmHg|||||||

Group:CN
Fields:|REFNO|CONDNR|CONDDATE|CONDTIME|HR|HRNR|HRSITE|CONDNAME|
|81013|1|30/11/2020|08:29:15||||Rest|

Group:IV
Fields:|REFNO|CONDNR|INTERV|AMOUNT|

Group:PV
Fields:|REFNO|CONDNR|SITE|PRESS1|SAMP1|PRESS2|SAMP2|PRESS3|SAMP3|

Group:SA
Fields:|REFNO|CONDNR|SITE|O2SAT|O2CONT|OXYTIME|PO2|

Group:VD
Fields:|REFNO|CONDNR|SITE|DPDT|DPDTP|MSPRE|MDPRE|SW|SWI|SP|SPI|LVNR|

Group:VG
Fields:|REFNO|CONDNR|VALVE|GRAD|VALVAREA|PERIOD|PREDIFF|SYSPDIFF|SIMPUB|VGNR|DURATION|VAIX|COTYPE|VALVA226|VALVA227|VALVA145|VALVA225|SITE1|SITE2|VAIX226|VAIX227|VAIX145|VAIX225|

Group:SG
Fields:|REFNO|CONDNR|SITE1|SITE2|GRAD|VALVAREA|PERIOD|PREDIFF|SYSPDIFF|SIMPUB|SGNR|

Group:CO
Fields:|REFNO|CONDNR|COTYPE|INJSITE|SAMPSITE|CO|COHR|COTIME|CI|INHERIT|SCONDNR|

Group:CF
Fields:|REFNO|CONDNR|O2CONS|O2CONSP|AVO2DIFF|O2CAP|CONHB|

Group:CP
Fields:|REFNO|CONDNR|PREDCO|COTYPE|CI|SV|SVI|PAR|SVR|TPR|PARIX|SVRIX|TPRIX|TPRTSR|REGSV|REGSVI|REGF|PARSVR|PARPRD|SVRPRD|TSR|TSRIX|TPAR|DPAR|APAR|FPAR|TTPR|DTPR|ATPR|FTPR|TPARIX|DPARIX|APARIX|FPARIX|TTPRIX|DTPRIX|ATPRIX|FTPRIX|TSVR|DSVR|

Group:SH
Fields:|REFNO|CONDNR|PAVO2D|SAVO2D|PF|SF|PFI|SFI|PSV|SSV|PSVI|SSVI|SITEMV|SATMV|SITEPA|SATPA|SITEPV|SATPV|SITESA|SATSA|LRRATIO|RLRATIO|LRFLOW|RLFLOW|PSRATIO|PO2MV|PO2PA|PO2PV|PO2SA|LRSFI|RLSFI|

Group:GM
Fields:|REFNO|CONDNR|SERIENR|MEASNR|GMTIME|DURATION|INFL|GRAD|

Group:SM
Fields:|REFNO|CONDNR|SERIENR|MEASNR|SMTIME|DURATION|INFL|PRE1|PRE2|PRE3|

Group:AM
Fields:|REFNO|CONDNR|SERIENR|MEASNR|AMTIME|DURATION|INFL|GRAD|PROXPRE|DISTPRE|PREDIFF|MONPRE|CO|AREA|

Group:GS
Fields:|REFNO|CONDNR|STUDYTYP|SERIENR|SCALE|PROXSITE|DISTSITE|NOMEA|NRINT|DURATION|MAXAMO|FIRSTGRA|LASTGRA|

Group:SS
Fields:|REFNO|CONDNR|STUDYTYP|SERIENR|SCALE|SITE|NOMEA|NRINT|DURATION|MAXAMO|DISPTYPE|FIPRE1|FIPRE2|FIPRE3|LAPRE1|LAPRE2|LAPRE3|

Group:VS
Fields:|REFNO|CONDNR|STUDYTYP|SERIENR|PROXSITE|DISTSITE|NOMEA|NRINT|DURATION|MAXAMO|FIRSTGRA|LASTGRA|PROXTYPE|DISTTYPE|MONSITE|MONTYPE|

Group:TS
Fields:|REFNO|SAMPNR|SAMPTIME|

Group:LCI
Fields:|REFNO|ATIME|CONDNR|INTERV1|AMOUNT1|INTERV2|AMOUNT2|INTERV3|AMOUNT3|INTERV4|AMOUNT4|CONDNAME|
|81013|08:29:15|1|||||||||Rest|

Group:LCF
Fields:|REFNO|ATIME|CONDNR|CO|ARTSIT|VENSIT|SAT1|SAT2|O2CONS|FICKHB|COHR|COVTIM|

Group:LCO
Fields:|REFNO|ATIME|CONDNR|COTYPE|COMEAN|SITE1|SITE2|CO1|CO2|CO3|CO4|CO5|COHR|COVTIM|INCLUDED|

Group:LSA
Fields:|REFNO|ATIME|PARTNR|CONDNR|TIME1|SITE1|SAT1|TIME2|SITE2|SAT2|TIME3|SITE3|SAT3|PSRATIO|LRRATIO|RLRATIO|SITEMV|SITEPA|SITEPV|SITESA|PO21|PO22|PO23|

Group:LPV
Fields:|REFNO|ATIME|CONDNR|SEQNR|RSEQNR|HR|HRSITE|

Group:LP1
Fields:|REFNO|SEQNR|CHANNEL|SITE|PRESS1|PRESS2|PRESS3|SCONDNR|RPRESS|ATIME|CONDNR|

Group:LP2
Fields:|REFNO|SEQNR|CHANNEL|SITE1|FPRESS1|FPRESS2|FPRESS3|SITE2|SPRESS1|SPRESS2|SPRESS3|SCONDNR|RPRESS|RPRESS1|ATIME|CONDNR|

Group:LP3
Fields:|REFNO|SEQNR|VALVE|GRAD|PREDIFF|VALVAREA|PERIOD|DURATION|

Group:LP4
Fields:|REFNO|SEQNR|SITE1|SITE2|GRAD|PREDIFF|VALVAREA|PERIOD|

Group:LP5
Fields:|REFNO|SEQNR|SITE|DPDT|DPDTP|MSPRE|MDPRE|

Group:LP6
Fields:|REFNO|SEQNR|PRS|SPO2|PRN|NIBPS|NIBPD|NIBPM|RESP|

Group:LPI
Fields:|REFNO|ATIME|CONDNR|STUDY|DURATION|AMOUNT|

Group:LPA
Fields:|REFNO|ATIME|CONDNR|STUDY|COMEAN|CO1|CO2|CO3|CO4|CO5|VALVAREA|

Group:LSY
Fields:|REFNO|ATIME|CONDNR|STUDY|PROXSITE|DISTSITE|

Group:XRAY
Fields:|REFNO|ATIME|PLANE|RLANG|CCANG|SID|MAG|MO|KV|MA|FPS|PW|TI|FO|LA|

Group:XRAYA
Fields:|REFNO|ATIME|PLANE|AD|SD|CF|NF|SC|ASD|IV|IFL|

Group:XRAYSUM
Fields:|REFNO|PLANE|DOSE|FLTIME|ALOAD|AFV|AFC|

Group:XRAYASUM
Fields:|REFNO|PLANE|SKNDS|LA|ADPFL|SKDFL|

Group:XRAYBSUM
Fields:|REFNO|SEQNO|DOSE|FLTIME|SKNDS|DATETIME|EVENTCMT|

Group:SPO2
Fields:|REFNO|SEQNO|ATIME|PR|O2|
|81013|16001|08:35|||
|81013|16002|08:39|||
|81013|16003|08:55|||
|81013|16004|09:18|||

Group:NIBP
Fields:|REFNO|SEQNO|ATIME|PR|SYST|DIAST|MEAN|
|81013|16001|08:35||136|81|99|
|81013|16002|08:39||121|79|93|
|81013|16003|08:55||108|71|83|
|81013|16004|09:18||112|68|83|

Group:RESP
Fields:|REFNO|SEQNO|ATIME|RESP|ETCO2|
|81013|16001|08:35|||
|81013|16002|08:39|||
|81013|16003|08:55|||
|81013|16004|09:18|||

Group:ALDRSCRE
Fields:|REFNO|SEQNO|ATIME|CNSNS|RESPRN|SKINCLR|O2SAT|MSCFN|CIRCLN|TAS|PAINSC|
|81013|16001|08:35|||||||||
|81013|16002|08:39|||||||||
|81013|16003|08:55|||||||||
|81013|16004|09:18|||||||||

Group:REC
Fields:|REFNO|SEQNO|VOLUME|RECID|

Group:LPM
Fields:|REFNO|SEQNO|ATIME|MEALBL|TOTINT|INT1|INT2|

Group:Q_AI
Fields:|REFNO|VERSION|ATYPE|ADATE|ANAME|ANALYST|IMGTYPE|IMGID|

Group:Q_IF
Fields:|REFNO|SEQNO|VERSION|DATASET|IMGTXT|IMGFILE|

Group:H_TAIL
Fields:|REFNO|DATCHK|PAPSIZ|L_MARG|R_MARG|T_MARG|B_MARG|REP_TYP|CND_1|CND_2|SIGN|

Group:HEX
Fields:|REFNO|VARNO|VARIX|VAL|

Group:HET
Fields:|REFNO|SEQNO|CHPTEXT|

Group:COX
Fields:|REFNO|SEQNO|COOR|

Group:CHPD
Fields:|REFNO|SEQNO|CHPCOD|

Group:C_TAIL
Fields:|REFNO|DATCHK|PAPSIZ|L_MARG|R_MARG|T_MARG|B_MARG|

Group:C_COX
Fields:|REFNO|SEQNO|COOR|

Group:C_HEX
Fields:|REFNO|VERS|SEQN|VAR1|VAR2|VAR3|VAR4|VAR5|VAR6|VAR7|VAR8|VAR9|VAR10|TEXT1|TEXT2|TEXT3|TEXT4|TEXT5|TEXT6|MULT|IRRE|INTER1|INTER2|INTER3|INTER4|INTER5|INTER6|INTER7|INTER8|INTER9|GRAF1|GRAF2|VFLOW|TORTU|ANGUL|SPASM|SITCOD|

Group:C_HET
Fields:|REFNO|SEQNO|COMTXT|

Group:C_DE
Fields:|REFNO|DOMINAN|

Group:C_LE
Fields:|REFNO|VERS|SEQN|SITE|STENOS|AHACLASS|SHAP|LENMM|LEXTENT|FLOW|FILLING|INTERV1|INTERV2|INTERV3|INTERV4|INTERV5|INTERV6|INTERV7|INTERV8|INTERV9|ECCENTR|LACCESS|CURVAT|BIFURC|OSTIAL|CALCIF|THROMBUS|SPASM|ECTASIA|ANEURYSM|AHACODE|GRAFT|

Group:C_CE
Fields:|REFNO|VERS|SEQN|GSITE|RSITE|DEGREE|

Group:C_GE
Fields:|REFNO|VERS|SEQN|GSITE|RSITE1|RSITE2|RSITE3|GSHAPE|GTYPE|

Group:_E_MARKE
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|EVSEQNO|

Group:_IBP
Fields:|REFNO|SEQNO|ATIME|CHANNEL|SITE|SYST|DIAST|MEAN|
|81013|16001|08:35|200|||||
|81013|16002|08:39|200|||||
|81013|16003|08:55|200|||||
|81013|16004|09:18|200|||||

Group:_VSCMN
Fields:|REFNO|SEQNO|ATIME|EVENTLBL|EVENTCMT|
|81013|16001|08:35|Vital Signs||
|81013|16002|08:39|Vital Signs||
|81013|16003|08:55|Vital Signs||
|81013|16004|09:18|Vital Signs||

Group:_EN2STU
Fields:|REFNO|CASEID|SENDNAME|SENDAPP|

Group:_ITEMUSG
Fields:|REFNO|SEQNO|TRANSID|AUTOTIME|STATUS|ITEMID|ETYPE|COMMENT|SERIALNO|LOTNO|

Group:_VMMUSG
Fields:|REFNO|SEQNO|AUTOTIME|STATUS|CODE|COMMENT|CTGRNAME|MANNAME|BRAND|ITEMID|SERIALNO|LOTNO|COST|CHARGE|CHRGCODE|CTLOGNUM|ACCSEQ|ACCCODE|ETYPE|TRANSID|

Group:_VPAINSC
Fields:|REFNO|SEQNO|ATIME|PAINSC|
|81013|16001|08:35:38||
|81013|16002|08:39:47||
|81013|16003|08:55:26||
|81013|16004|09:18:43||

Group:_FFR
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|FFRVALUE|SITE1|SITE2|PRO_MEAN|DIS_MEAN|EVNT_DUR|PRES_DIF|PDPAVAL|

Group:_M_FFR
Fields:|REFNO|CONDNR|DATETIME|EVENTLBL|EVENTCMT|FFRVALUE|SITE1|SITE2|PDPAVAL|

Group:_DIAGSTR
Fields:|REFNO|VCRXML|MODIFYDT|SAVEDBY|

Group:_CORONRY
Fields:|REFNO|DOMINAN|COMMENT|MODIFYDT|

Group:_GRAFDES
Fields:|REFNO|ASSESSED|GFCOMPLX|GRAFTID|GRAFTYPE|

Group:_GFTARGT
Fields:|REFNO|COMMENT|GRAFTSEG|IONSOFID|TORTOUSE|VESLCODE|VESLSEG|

Group:_INTRVEN
Fields:|REFNO|ASSOCITO|INTRVID|INTRVTYP|INTRVDAT|PREVINTR|

Group:_LESION
Fields:|REFNO|SEQNO|COMMENT|INGRAFT|IONSOFID|LENGTH|PRETIMI|POSTTIMI|RESIDUAL|SEVERITY|ULCERTED|VESLCODE|VESLSEG|LESNTYPE|AUTOTIME|

Group:_ABNORM
Fields:|REFNO|ABRNTYPE|COMMENT|IONSOFID|PRETIMI|POSTTIMI|SEVERITY|VESLCODE|VESLSEG|

Group:_VESLINF
Fields:|REFNO|CALIBER|COMMENT|DISTLFLW|IONSOFID|ASSESSED|TORTUOSE|VESLCODE|

Group:_CPTEMP
Fields:|REFNO|CONDNR|PREDCO|COTYPE|CI|SV|SVI|PAR|SVR|TPR|PARIX|SVRIX|TPRIX|TPRTSR|REGSV|REGSVI|REGF|PARSVR|PARPRD|SVRPRD|TSR|TSRIX|TPAR|DPAR|APAR|FPAR|TTPR|DTPR|ATPR|FTPR|TPARIX|DPARIX|APARIX|FPARIX|TTPRIX|DTPRIX|ATPRIX|FTPRIX|TSVR|DSVR|
|81013|1||THERMO|||||||||||||||||||||||||||||||||||||

Group:_LPVTEMP
Fields:|REFNO|ATIME|CONDNR|SEQNR|RSEQNR|HR|HRSITE|

Group:_SVI
Fields:|REFNO|CONDNR|SVIT|SVIA|SVID|SVIF|
|81013|1|||||

Group:_SAI
Fields:|REFNO|CONDNR|DATETIME|SEQNR|EVENTLBL|EVENTCMT|SAIVALUE|LVEXPARE|LVINSARE|RVEXPARE|RVINSARE|RVSPINSP|RVEDPINS|RVBDPINS|LVSPINSP|LVEDPINS|LVBDPINS|RVSPEXPR|RVEDPEXP|RVBDPEXP|LVSPEXPR|LVEDPEXP|LVBDPEXP|INSBEATN|EXPBEATN|

Group:_CLWIDTH
Fields:|REFNO|GRPNAME|COLWIDTH|

Group:CASETIME
Fields:|REFNO|SEQNO|AUTOTIME|EVENTTYP|COMMENT|
|81013|16001|08:33:20|Patient in room||
|81013|16003|08:44:30|Needle to skin||
|81013|16002|08:43:39|Time out performed||
|81013|16005|09:27:57|Patient out of room||
|81013|16004|09:20:20|Procedure Complete||

Group:_EVTPRD
Fields:|REFNO|EVTNO|SEQNR|PRSNID|REFEVNO|STATUS|DATETIME|EVENTCMT|

Group:_MAINSUB
Fields:|REFNO|MAINID|SUBID|SEQNR|DATETIME|EVENTCMT|

Group:_PCHILD
Fields:|REFNO|PARENTID|CHILDID|SEQNR|DATETIME|EVENTCMT|

Group:_EXCLUDD
Fields:|REFNO|EVENTID|SEQNR|DATETIME|EVENTCMT|

Group:_CN
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVTTIME|CONDNAME|INTERV1|AMOUNT1|INTERV2|AMOUNT2|INTERV3|AMOUNT3|INTERV4|AMOUNT4|COTYPE|INHERIT|EVENTCMT|
|81013|16001|1|08:29:15|08:29:15|Rest|||||||||THERMO|||

Group:_CNCHD
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|EVENTCMT|
|81013|16001|08:29:15|1||

Group:_PRESSUR
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVTTIME|SAMSEQNR|CHANNEL|SITE|SCONDNR|PRESS1|PRESS2|PRESS3|RPRESS|TSHIFT|PBAKPRSS|DPDT|DPDTP|EVENTCMT|

Group:_RECON
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|ANNOT|CALIPER|RETTIME|EVENTCMT|

Group:_RECOFF
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|ANNOT|CALIPER|EVENTCMT|

Group:_SNPSHOT
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|ANNOT|CALIPER|EVENTCMT|OPTHR|

Group:_STIMEX
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|LABEL|PECHA|NECHA|PECHB|NECHB|S1S1|S1S2|S2S3|S3S4|S4S5|

Group:_STIMCON
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|LABEL|PECHA|NECHA|PECHB|NECHB|PCL|

Group:_STIMCOF
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|

Group:_ABLATON
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|EVSEQNO|ANNOT|CALIPER|

Group:_ABLATOF
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|EVSEQNO|DURATION|AVTEMP|AVPOWER|AVIMPD|ENERGY|ANNOT|CALIPER|TEMPCNT|IMPCNT|POWCNT|MAXTEMP|MAXIMP|MAXPOW|TEMPSUM|IMPSUM|POWSUM|ABLTYPE|MINTEMP|MINIMP|MINPOW|

Group:_TACHYON
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|CL|ONSET|ANNOT|CALIPER|

Group:_TACHYOF
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|ANNOT|CALIPER|

Group:_BRADYON
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|CL|ONSET|ANNOT|CALIPER|

Group:_BRADYOF
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|ANNOT|CALIPER|

Group:_ECG12LD
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|MORPH|ANNOT|CALIPER|ESNPSHT|OPTHR|

Group:_INTERVL
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|INTERV1|INTERV2|INTERV3|INTERV4|INTERV5|INTERV6|INTERV7|INTERV8|INTLAB1|INTLAB2|INTLAB3|INTLAB4|INTLAB5|INTLAB6|INTLAB7|INTLAB8|ANNOT|CALIPER|

Group:_TXTNOTE
Fields:|REFNO|SEQNO|CRTTIME|EVENTCMT|

Group:_PRNTOUT
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|ANNTN|CALIPER|LABEL|OFFSET|ORGTIME|EVENTCMT|

Group:_TEMPLAT
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|ANNOT|CALIPER|EVENTCMT|

Group:_WAVEFRM
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|ANNOT|CALIPER|

Group:_HB
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|HB|EVENTCMT|

Group:_O2CONS
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|O2CONS|EVENTCMT|

Group:_O2SAT
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVTTIME|PARTNR|SITE1|SAT1|PO21|INCLUDED|EVENTCMT|

Group:_O2SATAV
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVTTIME|SITE|O2SAT|OXYTIME|PO2|EVENTCMT|

Group:_EVTCO
Fields:|REFNO|SEQNO|CRTTIME|COVALUE|EVENTCMT|

Group:_THERMO
Fields:|REFNO|SEQNO|CRTTIME|EVTTIME|CONDNR|COTYPE|COMEAN|SITE1|SITE2|CO1|COHR|INCLUDED|SV|THERMTYP|CATHTYPE|CATHSIZE|INJCTVOL|COMPCONS|INJETEMP|BLDTEMP|EVENTCMT|

Group:_DYE
Fields:|REFNO|SEQNO|CRTTIME|EVTTIME|CONDNR|COTYPE|COMEAN|SITE1|SITE2|CO1|COHR|INCLUDED|SV|EVENTCMT|

Group:_ANGIO
Fields:|REFNO|SEQNO|CRTTIME|EVTTIME|CONDNR|COTYPE|COMEAN|SITE1|CO1|COHR|INCLUDED|SV|EVENTCMT|

Group:_THERAVG
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVTTIME|COTYPE|INJSITE|SAMPSITE|CO|COHR|INHERIT|SCONDNR|CONAME|SV|EVENTCMT|

Group:_DYEAVG
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVTTIME|COTYPE|INJSITE|SAMPSITE|CO|COHR|INHERIT|SCONDNR|CONAME|SV|EVENTCMT|

Group:_ANGIAVG
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVTTIME|COTYPE|INJSITE|SAMPSITE|CO|COHR|INHERIT|SCONDNR|CONAME|SV|EVENTCMT|

Group:_FICK
Fields:|REFNO|SEQNO|CRTTIME|EVTTIME|CONDNR|HB|O2CONS|O2CONSMD|SAT2|SAT1|CO|PF|SF|RLFLOW|LRFLOW|RLRATIO|LRRATIO|PSRATIO|SV|PSV|SSV|VENSIT|ARTSIT|SITEPV|SITESA|LRSFI|RLSFI|COHR|SITEMV|SITEPA|AVO2DIFF|PAVO2D|SAVO2D|MVCONT|PACONT|PVCONT|SACONT|SATMV|SATPA|SATPV|

Group:_VLVGRAD
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|VALVE|PREDIFF|SYSPDIFF|GRAD|VALVA226|VALVA227|VALVA145|VALVA225|VGNR|DURATION|PERIOD|MSDPRE|SITE1|SITE2|PBAKGRAD|PSIGNAL1|PSIGNAL2|EVENTCMT|

Group:_VLVGDRS
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|VALVE|PREDIFF|SYSPDIFF|GRAD|VALVA145|VGNR|DURATION|PERIOD|MSDPRE|VALVA225|VALVA226|VALVA227|SITE1|SITE2|SIMPUB|PBAKGRAD|EVENTCMT|

Group:_SPLGRAD
Fields:|REFNO|SEQNO|CRTTIME|PREDIFF|SYSPDIFF|GRAD|SGNR|SEDDFD|SEPDFP|MEANDPRE|SITE1|SITE2|PBAKGRAD|PSIGNAL1|PSIGNAL2|EVENTCMT|

Group:_SPLGDRS
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|MEANDPRE|PREDIFF|SYSPDIFF|MEANGRAD|SGNR|SEDDFD|SEPDFP|SITE1|SITE2|SIMPUB|PBAKGRAD|EVENTCMT|

Group:_PRESSRS
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|SITE|PRESS1|PRESS2|PRESS3|DPDT|DPDTP|SAMPNR|EVENTCMT|

Group:_XRAYAB
Fields:|REFNO|SEQNO|CRTTIME|EVTTIME|PLANE|RLANG|CCANG|SID|MAG|MO|KV|MA|FPS|PW|TI|FO|AD|SD|CF|NF|SC|ASD|IV|IFL|LA|EVENTCMT|

Group:_XRAYSUM
Fields:|REFNO|SEQNO|CRTTIME|PLANE|DOSE|FLTIME|AFV|AFC|SKNDS|LA|ADPFL|SKDFL|TOTADOSE|TOTFLTIM|TOTSKNDS|EVENTCMT|

Group:_DERDATA
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|BSA|SW|SWLV|SWI|SWILV|SP|SPLV|SPI|SPILV|REGF|REGSV|REGSVI|PAR|TPR|PARIX|TPRIX|SVR|TSR|SVRIX|TSRIX|TPRTSR|PARSVR|CI|CIDYE|CIANG|CIFICK|PFI|SFI|LRSFI|RLSFI|SVI|SVIDYE|SVIANG|SVIFICK|PSVI|SSVI|
|81013|16001|08:29:16|1|1.966415||||||||||||||||||||||||||||||||||||

Group:_PRESCAL
Fields:|REFNO|SEQNO|CRTTIME|EVTTIME|CONDNR|ANNOT|BLIPS|HR|HRSITE|HRNR|ERREASON|INTERV1|INTERV2|INTERV3|INTERV4|EVENTCMT|

Group:_XRAYIMG
Fields:|REFNO|SEQNO|CRTTIME|PLANE|RALAANG|CRCAANG|IMGNUM|EVENTCMT|

Group:_STARTAT
Fields:|REFNO|SEQNO|CRTTIME|EVENTCMT|

Group:_STOPAT
Fields:|REFNO|SEQNO|CRTTIME|EVENTLBL|INFLPRE|INFDUR|INFLDUR|EVENTCMT|

Group:_STARTVT
Fields:|REFNO|SEQNO|CRTTIME|EVENTCMT|

Group:_STOPVT
Fields:|REFNO|SEQNO|CRTTIME|EVENTLBL|INFLPRE|INFDUR|INFLDUR|EVENTCMT|

Group:_STARCUT
Fields:|REFNO|SEQNO|CRTTIME|EVENTLBL|ELAPSET|ELAPSED|EVENTCMT|

Group:_STOPCUT
Fields:|REFNO|SEQNO|CRTTIME|EVENTLBL|ELAPSET|ELAPSED|EVENTCMT|

Group:_STARCDT
Fields:|REFNO|SEQNO|CRTTIME|EVENTLBL|ELAPSET|ELAPSED|EVENTCMT|

Group:_STOPCDT
Fields:|REFNO|SEQNO|CRTTIME|EVENTLBL|ELAPSET|ELAPSED|EVENTCMT|

Group:_VSIGNS
Fields:|REFNO|SEQNO|CRTTIME|EVTTIME|SYST|DIAST|MEAN|O2|RESP|PR|SITE|PSIGNAL|CNSNS|RESPRN|SKINCLR|O2SAT|MSCFN|CIRCLN|TAS|ETCO2|IBPSYST|IBPDIAST|IBPMEAN|IBPINCL|PAINSC|PRSTAT|SYSTSTAT|DIASSTAT|MEANSTAT|O2STAT|RRSTAT|ETCOSTAT|IBPSYSTS|IBPDIASS|IBPMEANS|EVENTLBL|EVENTCMT|
|81013|16001|08:35|08:35|136|81|99|||||200||||||||||||0||1|0|0|0|2|2|2|2|2|2|Vital Signs||
|81013|16002|08:39|08:39|121|79|93|||||200||||||||||||0||1|0|0|0|2|2|2|2|2|2|Vital Signs||
|81013|16003|08:55|08:55|108|71|83|||||200||||||||||||0||1|0|0|0|2|2|2|2|2|2|Vital Signs||
|81013|16004|09:18|09:18|112|68|83|||||200||||||||||||0||1|0|0|0|2|2|2|2|2|2|Vital Signs||

Group:_STIMDON
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|LABEL|PECHA|NECHA|PECHB|NECHB|PCLSTART|

Group:_STIMDOF
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|EVENTCMT|LABEL|PECHA|NECHA|PECHB|NECHB|PCLSTART|PCLSTOP|NOPULSES|

Group:_ABLASUM
Fields:|REFNO|SEQNO|CRTTIME|EVENTLBL|NOABLS|DURATION|AVTEMP|MAXTEMP|AVIMPD|MAXIMPD|AVPOWER|MAXPOWER|ENERGY|TTMPCNT|TTMPSUM|TIMPCNT|TIMPSUM|TPWRCNT|TPWRSUM|EVENTCMT|

Group:_HMAPIMG
Fields:|REFNO|SEQNO|CRTTIME|IMGNAME|IMGCMT|FILENAME|IMGSIZE|IMGTYPE|BLOBLINK|EVENTCMT|

Group:_VPBHPLE
Fields:|REFNO|SEQNO|CRTTIME|EVTTIME|CONDNR|SAMPLNUM|HR|HRSITE|ANNOT|BLIPS|INTERV1|INTERV2|INTERV3|INTERV4|ERREASON|HRSITENM|EVENTCMT|

Group:_ESSTIM
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVENTLBL|INPCHA|OUTSITE|S1S1|S1S2|S2S3|S3S4|S4S5|ANNOT|CALIPER|EVENTCMT|

Group:_CSTIMON
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|EVENTLBL|INPCHA|OUTSITE|PCL|ANNOT|CALIPER|EVENTCMT|

Group:_CSTIMOF
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|EVENTLBL|INPCHA|OUTSITE|PCL|ANNOT|CALIPER|EVENTCMT|

Group:_DSTIMON
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|EVENTLBL|INPCHA|OUTSITE|PCLSTART|ANNOT|CALIPER|EVENTCMT|

Group:_DSTIMOF
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|EVENTLBL|INPCHA|OUTSITE|PCLSTART|PCLSTOP|NOPULSES|ANNOT|CALIPER|EVENTCMT|

Group:_ABGRAPH
Fields:|REFNO|SEQNO|CRTTIME|EVENTLBL|FILENAME|BLOBLINK|BLOBBYTE|EVENTCMT|

Group:_MARKEVT
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|EVENTLBL|EVSEQNO|ANNOT|CALIPER|EVENTCMT|

Group:_LPRTOUT
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|ANNTN|CALIPER|LABEL|OFFSET|ORGTIME|EVENTCMT|

Group:_RPRTOUT
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|ANNTN|CALIPER|LABEL|OFFSET|ORGTIME|EVENTCMT|

Group:_SPRTOUT
Fields:|REFNO|SEQNO|CRTTIME|CONDNR|LSPERC|EVENTCMT|

Group:_VSALARM
Fields:|REFNO|SEQNO|CRTTIME|VSLABEL|ALMSTAT|AUDSTAT|VSVALUE|VSLIMIT|OFFREASN|PSIGNAL|SITE|EVENTCMT|

Group:_VSASTNG
Fields:|REFNO|SEQNO|CRTTIME|ALTYPE|HRALSTAT|SPALSTAT|RESPSTAT|ETCOSTAT|NBPMSTAT|IBPMSTAT|SITE|PSIGNAL|EVENTCMT|
|81013|16001|08:29:16|Active/Adult|On:On:45:120|Off|Off|Off|Off|Off||||

Group:_FFR1
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVTTIME|EVENTLBL|EVENTCMT|FFRVALUE|SITE1|SITE2|PRO_MEAN|DIS_MEAN|EVNT_DUR|PRES_DIF|PSIGNAL1|PSIGNAL2|USERFFR|EVTBYFFR|PDPAVAL|

Group:_M_FFR1
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|EVTTIME|EVENTLBL|EVENTCMT|FFRVALUE|SITE1|SITE2|PDPAVAL|

Group:_SAINDEX
Fields:|REFNO|SEQNO|CONDNR|CRTTIME|ESEQNR|EVENTLBL|EVENTCMT|SAIVALUE|LVEXPARE|LVINSARE|RVEXPARE|RVINSARE|RVSPINSP|RVEDPINS|RVBDPINS|LVSPINSP|LVEDPINS|LVBDPINS|RVSPEXPR|RVEDPEXP|RVBDPEXP|LVSPEXPR|LVEDPEXP|LVBDPEXP|INSBEATN|EXPBEATN|ANNTN|BLIPS|INTRV1|INTRV2|INTRV3|INTRV4|

Group:_EXPWFD
Fields:|REFNO|SEQNO|CRTTIME|EWFDESC|EWFSTTIM|EWFSPTIM|EWFFLSIZ|EVENTCMT|

Group:_MPNGPNT
Fields:|REFNO|SEQNO|CRTTIME|ANNTN|CALIPER|MAPID|MPGUID|MPPNTID|MAPNAME|MAPLAT|MAPTAG|MAPTYPE|UNIPOLAR|BIPOLAR|MAPCMNT|EVENTCMT|

Group:_INTRNAL
Fields:|REFNO|SEQNO|CRTTIME|ORGSTUID|LARTISID|EMGSTAT|ACTSTDUR|MAPSTUID|EVENTCMT|
|81013|16001|08:29:15|1.3.12.2.1107.5.13.2.0.30000020111519210138500000130|1.3.12.2.1107.5.13.2.0.30000020111519210138500000130|0|3526|||

